### ISSUE TITLE
What is the video_data path?

### ISSUE THREAD

**Issue by kminemur** [yanbeic/Deep-Association-Learning#1]
Hi, I'm not clear about data conversion script.
Can you give me some tips for data conversion?

The written path in "tf_convert_data.sh" is different from the downloaded file structure.

# Written path
DATA_DIR=YOUR_DATA_PATH/PRID2011/video_data/

# My datapath
(venv) ros@ros-Z170X-UD5:~/VideoData/PRID2011$ tree -L 2
.
├── multi_shot
│   ├── cam_a
│   └── cam_b
├── readme.txt
├── single_shot
│   ├── cam_a
│   └── cam_b
└── train_test_split
    ├── readme.txt
    ├── train_test_splits_ilidsvid.mat
    └── train_test_splits_prid.mat

When setting DATA_DIR=VideoData/PRID2011/single_shot/, I got
  
IOError: [Errno 2] No such file or directory: 'YOUR_DATA_PATH/PRID2011/single_shot/cam1/person_0044/0071.png'

**Comment by yanbeic** [comment]
Hi,

You may rename your downloaded data folders to fit with the scripts: 
"multi_shot/cam_a" -> "video_data/cam1"
"multi_shot/cam_b" -> "video_data/cam2"

**Comment by kminemur** [comment]
it works thank you
